# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        ('tellers', '0003_delete_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('phone number', models.CharField(max_length=10)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.Bank')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
