# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tellers', '0004_auto_20171108_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tellers',
            new_name='Teller',
        ),
    ]
