# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account number',
            field=models.UUIDField(),
        ),
    ]
