# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20171108_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account number',
            field=models.UUIDField(editable=False),
        ),
    ]
