# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20171108_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account number',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
    ]
